### ISSUE TITLE
PyGame is Down

### ISSUE THREAD

**Issue by kjaymiller** [Python-Community-News/Topics#104]
### URL

https://github.com/pygame/pygameweb/issues/131

### When was this post released

11 Jan 2023

### Summary

Users are taking to r/python as well as the official PyGame website repo after getting a 500 error on the website. There currently has not been any official word from the maintainers on their Twitter or Mastodon accounts.
 

### Code of Conduct

- [ ] I would like my name mentioned on the podcast
- [X] I agree to follow this project's Code of Conduct

**Comment by jefftriplett** [comment]
It looks like it's back up. I'm not seeing a reason for it going down in that issue.

**Comment by kjaymiller** [comment]
Yeah not sure... We can go ahead and close this then.
