### ISSUE TITLE
[FIX] Issue Template for New Topics is not labeling new topics with the content label

### ISSUE THREAD

**Issue by kjaymiller** [Python-Community-News/Topics#13]
If you use the new topic template, it is not adding the content label. This functionality most likely broke when porting from the original repo.

# To Fix
Edit the [yaml template file](https://github.com/Python-Community-News/Topics/blob/main/.github/ISSUE_TEMPLATE/add_news_topic.yml) and add the `content` label to the `labels` section. If it already exists. I suggest removing and adding it (**all lowercase**)

**Comment by jonafato** [comment]
Do we need this label now that Topics is its own repository? That should be the vast majority of stuff here, right?

**Comment by kjaymiller** [comment]
We also have conferences. I don't think it's entirely necessary but if we wanted to do a similar GH Projects like we did in the previous repo would need the labels for filtering.

**Comment by jonafato** [comment]
Cool, works for me, just making sure we're not keeping obsolete features around after transitioning to the new repo.
