### ISSUE TITLE
As a community should we be helping build an ecosystem of Central Bank Digital Currencies (CBDC's)

### ISSUE THREAD

**Issue by Back2Basics** [Python-Community-News/Topics#47]
### URL

https://www.whitehouse.gov/briefing-room/statements-releases/2022/09/16/fact-sheet-white-house-releases-first-ever-comprehensive-framework-for-responsible-development-of-digital-assets/

### Summary

The programming communities are going to be asked to get involved with nationalizing cryptocurrencies. Should we push back on programmable money at the national level as a community?
Topic points:

What happens when a central authority has this type of power with programmable money? (incentive programs, deterrent programs)
Differences between decentralized cryptocurrencies (bitcoin, etherium) and CBDC's
links:

https://www.whitehouse.gov/briefing-room/statements-releases/2022/09/16/fact-sheet-white-house-releases-first-ever-comprehensive-framework-for-responsible-development-of-digital-assets/
https://www.csis.org/blogs/new-perspectives-asia/chinas-progress-towards-central-bank-digital-currency

### Code of Conduct

- [ ] I would like my name mentioned on the podcast
- [X] I agree to follow this project's Code of Conduct

**Comment by kjaymiller** [comment]
Thanks for submitting this topic. Sadly it's not connected to any current news piece (the article you mentioned was back in September). We will definitely tag and save this in case we do a bigger conversation.
